export const membersData = [
    {
        id: 1,
        src: "/Image/boardMember1.WEBP",
        name: "Mr. Anand Kumar",
        position: "Program Head",
        desc: "Mr. Anand Kumar oversees all program activities, ensuring the organization's objectives are met with precision and passion.",
        date: "31st June, 2021",
        member: "Board Member",
    },
    {
        id: 2,
        src: "/Image/boardMember2.WEBP",
        name: "Dr. Sunita Sharma",
        position: "Director of Education",
        desc: "Dr. Sharma brings decades of experience in education, leading innovative learning programs for underprivileged students.",
        date: "15th August, 2020",
        member: "Board Member",
    },
    {
        id: 3,
        src: "/Image/boardMember3.WEBP",
        name: "Mr. Rajesh Singh",
        position: "Treasurer",
        desc: "With expertise in financial planning, Mr. Singh ensures transparent and efficient use of organizational funds.",
        date: "12th January, 2019",
        member: "Board Member",
    },
    {
        id: 4,
        src: "/Image/boardMember4.WEBP",
        name: "Ms. Priya Agarwal",
        position: "Community Outreach Coordinator",
        desc: "Ms. Agarwal is dedicated to bridging the gap between the organization and the communities it serves.",
        date: "7th October, 2022",
        member: "Student",
    },
    {
        id: 5,
        src: "/Image/boardMember5.WEBP",
        name: "Mr. Arjun Mehta",
        position: "Technology Advisor",
        desc: "Mr. Mehta leverages his technological expertise to bring innovation and efficiency to the foundation's operations.",
        member: "Student",
        date: "25th April, 2021",
    },
    {
        id: 6,
        src: "/Image/boardMember6.WEBP",
        name: "Ms. Kavita Joshi",
        position: "Project Manager",
        desc: "Ms. Joshi leads multiple projects, ensuring timely completion and aligning them with the foundation's mission.",
        member: "Student",
        date: "3rd March, 2023",
    },
    {
        id: 7,
        src: "/Image/boardMember2.WEBP",
        name: "Dr. Sunita Sharma",
        position: "Director of Education",
        desc: "Dr. Sharma brings decades of experience in education, leading innovative learning programs for underprivileged students.",
        date: "15th August, 2020",
        member: "Board Member",
    },
    {
        id: 8,
        src: "/Image/boardMember4.WEBP",
        name: "Ms. Priya Agarwal",
        position: "Community Outreach Coordinator",
        desc: "Ms. Agarwal is dedicated to bridging the gap between the organization and the communities it serves.",
        date: "7th October, 2022",
        member: "Board Member",
    },
    {
        id: 9,
        src: "/Image/boardMember1.WEBP",
        name: "Mr. Anand Kumar",
        position: "Program Head",
        desc: "Mr. Anand Kumar oversees all program activities, ensuring the organization's objectives are met with precision and passion.",
        date: "31st June, 2021",
        member: "Student",
    },

];
